.PHONY: clean All

All:
	@echo "----------Building project:[ STREAMING - Debug ]----------"
	@"$(MAKE)" -f  "STREAMING.mk"
clean:
	@echo "----------Cleaning project:[ STREAMING - Debug ]----------"
	@"$(MAKE)" -f  "STREAMING.mk" clean
